---
# Source: zeebe-cluster/templates/gateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "default-zeebe-gateway"
  labels:
    app.kubernetes.io/name: zeebe-cluster
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
  annotations:
    null
spec:
  selector:
      app.kubernetes.io/name: zeebe-cluster
      app.kubernetes.io/instance: default
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/component: gateway
  ports:
    - port: 9600
      protocol: TCP
      name: http
    - port: 26500
      protocol: TCP
      name: gateway
